server:
  port: 8004
spring:
  application:
    name: zipkin
eureka:
  instance:
    appname: 链路追踪服务
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka


management:
  metrics:
    web:
      server:
        auto-time-requests: false